apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: k-s-kafka
build:
  artifacts:
  - image: carrier
    context: services/carrier
    docker:
      dockerfile: dockerfile
  - image: shop
    context: services/shop
    docker:
      dockerfile: dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/carrier-definition.yml
    - k8s/shop-definition.yml
